################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Security Platform Flink Configuration

#==============================================================================
# Common
#==============================================================================

# Job Manager配置
jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
jobmanager.bind-host: 0.0.0.0
jobmanager.memory.process.size: 1600m
jobmanager.memory.flink.size: 1280m

# Task Manager配置
taskmanager.bind-host: 0.0.0.0
taskmanager.rpc.port: 6122
taskmanager.memory.process.size: 1728m
taskmanager.memory.flink.size: 1280m
taskmanager.numberOfTaskSlots: 4

# 并行度配置
parallelism.default: 2
jobmanager.execution.failover-strategy: region

#==============================================================================
# Checkpointing
#==============================================================================

# 检查点配置
state.backend: filesystem
state.checkpoints.dir: file:///tmp/flink-checkpoints
state.savepoints.dir: file:///tmp/flink-savepoints

# 检查点间隔（毫秒）
execution.checkpointing.interval: 60000
execution.checkpointing.min-pause: 30000
execution.checkpointing.timeout: 600000
execution.checkpointing.max-concurrent-checkpoints: 1
execution.checkpointing.prefer-checkpoint-for-recovery: true

#==============================================================================
# High Availability
#==============================================================================

# 高可用配置（单机模式暂时禁用）
# high-availability: zookeeper
# high-availability.zookeeper.quorum: zookeeper:2181
# high-availability.storageDir: file:///tmp/flink-ha

#==============================================================================
# Fault tolerance and checkpointing
#==============================================================================

# 重启策略
restart-strategy: failure-rate
restart-strategy.failure-rate.max-failures-per-interval: 3
restart-strategy.failure-rate.failure-rate-interval: 5 min
restart-strategy.failure-rate.delay: 10 s

#==============================================================================
# Rest & web frontend
#==============================================================================

# Web UI配置
rest.port: 8081
rest.bind-address: 0.0.0.0
web.submit.enable: true
web.cancel.enable: true

#==============================================================================
# Advanced
#==============================================================================

# 网络配置
io.tmp.dirs: /tmp

# 心跳配置
heartbeat.interval: 10000
heartbeat.timeout: 50000

# 日志配置
env.log.dir: /opt/flink/log

# 类路径配置
env.java.opts: -Djava.awt.headless=true

# 安全配置
security.ssl.enabled: false

# 度量配置
metrics.reporters: slf4j
metrics.reporter.slf4j.class: org.apache.flink.metrics.slf4j.Slf4jReporter
metrics.reporter.slf4j.interval: 60 SECONDS

# Blob服务配置
blob.server.port: 6124
blob.service.cleanup.interval: 3600

# 历史服务配置
historyserver.web.address: 0.0.0.0
historyserver.web.port: 8082
historyserver.archive.fs.dir: file:///tmp/flink-completed-jobs
historyserver.archive.fs.refresh-interval: 10000